remove lsb dependencies

diff --git a/data/export/initscript/master.erb b/data/export/initscript/master.erb
--- a/data/export/initscript/master.erb
+++ b/data/export/initscript/master.erb
@@ -26,14 +26,6 @@ ENVIRONMENT=production
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-# Load the VERBOSE setting and other rcS variables
-[ -r /lib/init/vars.sh ] && . /lib/init/vars.sh
-
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
-# and status_of_proc is working.
-[ -r /lib/lsb/init-functions ] &&. /lib/lsb/init-functions
-
 #
 # Function that starts the daemon/service
 #
@@ -104,19 +96,19 @@ do_status()
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && echo "Starting $DESC" "$NAME"
 	do_start
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0|1) [ "$VERBOSE" != no ] && echo success ;;
+		2) [ "$VERBOSE" != no ] && echo failed ;;
 	esac
 	;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && echo "Stopping $DESC" "$NAME"
 	do_stop
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0|1) [ "$VERBOSE" != no ] && echo success ;;
+		2) [ "$VERBOSE" != no ] && echo failed ;;
 	esac
 	;;
   status)
@@ -136,26 +128,25 @@ case "$1" in
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
 	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
+	echo "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
 	  0|1)
 		do_start
 		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
+			0) echo success ;;
+			1) echo "old process is still running" ;; # Old process is still running
+			*) echo failed ;; # Failed to start
 		esac
 		;;
 	  *)
 	  	# Failed to stop
-		log_end_msg 1
+		echo "failed to stop"
 		;;
 	esac
 	;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
 	exit 3
 	;;
 esac
